name: Pack Endstone
on:
  workflow_dispatch:
    inputs:
      Endstone:
        description: 'Endstone version'
        required: true
        default: '0.5.0'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    permissions:
      contents: write
    runs-on: windows-latest
    steps: 
    - name: Check Out
      uses: actions/checkout@v4
    - name: Download Endstone
      run: |
        Invoke-WebRequest -Uri https://github.com/EndstoneMC/endstone/releases/download/v${{ github.event.inputs.Endstone }}/endstone-win_amd64-portable.zip -OutFile Endstone.zip 
        7z x Endstone.zip -oEndstone-releases
    - name: Download PeEditor&PreLoader
      run: |
        mkdir Endstone
        cd Endstone
        ../lip install -y github.com/LiteLDev/PeEditor
        ../lip install -y github.com/LiteLDev/PreLoader
        cd ..
    - name: Copy files
      run: |
        cd Endstone
        mkdir plugins/endstone
        Copy-Item -Path "../Endstone-releases/bin/python/*" -Destination "plugins/endstone" -Recurse
        echo '{"name": "endstone","entry": "Lib/site-packages/endstone/_internal/endstone_runtime.dll","version": ${{ github.event.inputs.Endstone }},"type": "preload-native"}' > plugins/endstone/manifest.json
        cd ..
    - name: Pack files
      run: |
        cd Endstone
        7z a -tzip "Endstone-${{ github.event.inputs.Endstone }}.zip" .
        copy "Endstone-${{ github.event.inputs.Endstone }}.zip" ..
        cd ..
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: "Endstone-${{ github.event.inputs.Endstone }}.zip" 
        name: Endstone-${{ github.event.inputs.Endstone }}
        tag_name: ${{ github.event.inputs.Endstone }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
